# RAPP API Travis Continuous Integration Configuration File
# Author: Maria Ramos <m.ramos@ortelio.co.uk>
# 
language: g++ 
sudo: required
dist: xenial
compiler:
    - g++
os:
    - linux

branches:
    only:
    - master

#branches:
#    except:
#    - master

before_install: 
    - sudo apt-get update -y
    - sudo apt-get install gcc g++ libboost-all-dev cmake git -y

install: true

script:
    - mkdir -p build
    - cd build
    - cmake .. -DBUILD_TESTS=ON 
    - make
    - sudo make install
    - make test
