# RAPP API Travis Continuous Integration Configuration File
# Author: Maria Ramos <m.ramos@ortelio.co.uk>
# 
language: g++ 
sudo: required
dist: xenial
compiler:
    - g++
os:
    - linux

branches:
    only:
    - master

before_install: 
    - sudo apt-get update -y
    - sudo apt-get install gcc g++-6 libboost-all-dev cmake git -y
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10
    - sudo update-alternatives --set g++ /usr/bin/g++-6

install: true

script:
    - mkdir -p build
    - cd build
    - cmake .. -DBUILD_TESTS=ON 
    - make
    - sudo make install
    - make test
