#include <noos/objects/audio.hpp>
#include <noos/objects/face.hpp>
#include <noos/objects/human.hpp>
#include <noos/objects/picture.hpp>
#include <noos/objects/point.hpp>
#include <noos/objects/time.hpp>
#include <noos/objects/qr_code.hpp>
#include <noos/objects/orb_object.hpp>
#include <noos/objects/pose.hpp>
#include <noos/objects/laser.hpp>
#include <noos/objects/orientation.hpp>
#include <noos/objects/config_file.hpp>
