services:
  list:
    - available_services
    - speech_detection_sphinx4
    - speech_detection_google
    - qr_detection
    - face_detection
    - set_noise_profile
    - ontology_subclasses_of
    - ontology_superclasses_of
    - ontology_is_subsuperclass_of
    - detect_objects
    - cognitive_test_chooser
    - cognitive_record_performance
    - text_to_speech
    - cognitive_get_scores
    - cognitive_get_history
    - user_personal_info
