#include <rapp/objects/human.hpp>
#include <rapp/objects/face.hpp>
#include <rapp/objects/qr_code.hpp>
#include <rapp/objects/picture.hpp>
#include <rapp/objects/audio.hpp>
#include <rapp/objects/time.hpp>
#include <rapp/objects/point.hpp>
#include <rapp/objects/quaternion.hpp>
#include <rapp/objects/pose.hpp>
#include <rapp/objects/msg_metadata.hpp>
#include <rapp/objects/pose_stamped.hpp>
#include <rapp/objects/planned_path.hpp>
#include <rapp/objects/orb_object.hpp>
